=== GeorgiKhomeriki/Alitheia-Core/metrics/simulation/src/eu/sqooss/metrics/simulation/xml/SimulationSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.example.org/SimulationSchema"
	xmlns:tns="http://www.example.org/SimulationSchema"
	elementFormDefault="qualified">







	<complexType name="ModuleType">
		<sequence>
			<element name="name" type="string" maxOccurs="1"
				minOccurs="1">
			</element>
			<element name="numberOfPieces" type="int"
				maxOccurs="unbounded" minOccurs="1">
			</element>
		</sequence>
	</complexType>

	<complexType name="ModulesType">
		<sequence>
			<element name="module" type="tns:ModuleType"
				maxOccurs="unbounded" minOccurs="1">
			</element>
		</sequence>
	</complexType>



	<complexType name="SimulationSpecificParametersType">
		<sequence>
			<element name="simulationSteps" type="int" maxOccurs="1"
				minOccurs="1">
			</element>
			<element name="numberOfRepetitions" type="int" maxOccurs="1"
				minOccurs="1">
			</element>
			<element name="timeScale" type="double" maxOccurs="1"
				minOccurs="1">
			</element>
		</sequence>
	</complexType>

	<complexType name="InitialConditionsType">
		<sequence>
			<element name="modules" type="tns:ModulesType" maxOccurs="1"
				minOccurs="1">
			</element>
			<element name="simulationParameters"
				type="tns:SimulationSpecificParametersType" maxOccurs="1"
				minOccurs="1">
			</element>
		</sequence>
	</complexType>

	<complexType name="SubmissionInterestType">
		<sequence>
			<element name="interest" type="double" maxOccurs="unbounded"
				minOccurs="1">
			</element>
		</sequence>
	</complexType>

	<complexType name="DebuggingInterestType">
		<sequence>
			<element name="interest" type="double" maxOccurs="unbounded"
				minOccurs="1">
			</element>
		</sequence>
	</complexType>

	<complexType name="TestingInterestType">
		<sequence>
			<element name="interest" type="double" maxOccurs="unbounded"
				minOccurs="1">
			</element>
		</sequence>
	</complexType>

	<complexType name="FunctionalityInterestType">
		<sequence>
			<element name="interest" type="double" maxOccurs="unbounded"
				minOccurs="1">
			</element>
		</sequence>
	</complexType>

	<complexType name="ProgrammersInterestType">
		<sequence>
			<element name="submissionInterest"
				type="tns:SubmissionInterestType" maxOccurs="1" minOccurs="1">
			</element>
			<element name="debuggingInterest"
				type="tns:DebuggingInterestType" maxOccurs="1" minOccurs="1">
			</element>
			<element name="testingInterest"
				type="tns:TestingInterestType" maxOccurs="1" minOccurs="1">
			</element>
			<element name="functionalityInterest"
				type="tns:FunctionalityInterestType" maxOccurs="1" minOccurs="1">
			</element>
		</sequence>
	</complexType>


	<complexType name="TaskParametersType">
		<sequence>
			<element name="releaseFrequency" type="double" maxOccurs="1"
				minOccurs="1">
			</element>
			<element name="locIncrementMean" type="double" maxOccurs="1"
				minOccurs="1">
			</element>
			<element name="commitsMean" type="double" maxOccurs="1"
				minOccurs="1">
			</element>
		</sequence>
	</complexType>

	<complexType name="CalibrationParametersType">
		<sequence>
			<element name="commitsMean" type="double" maxOccurs="1"
				minOccurs="1">
			</element>
			<element name="releasesMean" type="double" maxOccurs="1"
				minOccurs="1">
			</element>
			<element name="contributorsMean" type="double" maxOccurs="1"
				minOccurs="1">
			</element>
			<element name="locIncremetsMean" type="int" maxOccurs="1"
				minOccurs="1">
			</element>
		</sequence>
	</complexType>

	<complexType name="BMFixedParametersType">
		<sequence>
			<element name="programmersInterest"
				type="tns:ProgrammersInterestType" maxOccurs="1" minOccurs="1">
			</element>
			<element name="tasks" type="tns:TaskParametersType"
				maxOccurs="1" minOccurs="1">
			</element>
			<element name="calibration"
				type="tns:CalibrationParametersType" maxOccurs="1" minOccurs="1">
			</element>
		</sequence>
	</complexType>


	<complexType name="AParametersType">
		<sequence>
			<element name="coreContributors" type="int" maxOccurs="1"
				minOccurs="1">
			</element>
			<element name="halfLifeOfProgrammersInterest" type="double"
				maxOccurs="1" minOccurs="1">
			</element>
			<element name="halfLifesStDev" type="double" maxOccurs="1"
				minOccurs="1">
			</element>
		</sequence>
	</complexType>

	<complexType name="BParametersType">
		<sequence>
			<element name="qZero" type="double" maxOccurs="1"
				minOccurs="1">
			</element>
		</sequence>
	</complexType>

	<complexType name="CParametersType">
		<sequence>
			<element name="projectReleaseInterval" type="int"
				maxOccurs="1" minOccurs="1">
			</element>
		</sequence>
	</complexType>

	<complexType name="BMProjectParametersType">
		<sequence>
			<element name="aParameters" type="tns:AParametersType"
				maxOccurs="1" minOccurs="1">
			</element>
			<element name="bParameters" type="tns:BParametersType"
				maxOccurs="1" minOccurs="1">
			</element>
			<element name="cParameters" type="tns:CParametersType"
				maxOccurs="1" minOccurs="1">
			</element>
		</sequence>
	</complexType>

	<complexType name="ModulesLOCMeanType">
		<sequence>
			<element name="moduleLOCMean" type="int"
				maxOccurs="unbounded" minOccurs="1">
			</element>
		</sequence>
	</complexType>

	<complexType name="ModulesLOCStDevType">
		<sequence>
			<element name="moduleLOCStDev" type="int"
				maxOccurs="unbounded" minOccurs="1">
			</element>
		</sequence>
	</complexType>

	<complexType name="CompletedLOCMeanType">
		<sequence>
			<element name="completedLOCMean" type="double"
				maxOccurs="unbounded" minOccurs="1">
			</element>
		</sequence>
	</complexType>

	<complexType name="CompletedLOCStDevType">
		<sequence>
			<element name="completedLOCStDev" type="double"
				maxOccurs="unbounded" minOccurs="1">
			</element>
		</sequence>
	</complexType>

	<complexType name="FuncImpLOCMeanType">
		<sequence>
			<element name="funcImpLOCMean" type="double"
				maxOccurs="unbounded" minOccurs="1">
			</element>
		</sequence>
	</complexType>

	<complexType name="FuncImpLOCStDevType">
		<sequence>
			<element name="funcImpLOCStDev" type="double"
				maxOccurs="unbounded" minOccurs="1">
			</element>
		</sequence>
	</complexType>

	<complexType name="LinesOfCodeParametersType">
		<sequence>
			<element name="ModulesLOCMean" type="tns:ModulesLOCMeanType"
				maxOccurs="1" minOccurs="1">
			</element>
			<element name="ModulesLOCStDev"
				type="tns:ModulesLOCStDevType" maxOccurs="1" minOccurs="1">
			</element>
			<element name="CompletedLOCMean"
				type="tns:CompletedLOCMeanType" maxOccurs="1" minOccurs="1">
			</element>
			<element name="CompletedLOCStDev"
				type="tns:CompletedLOCStDevType" maxOccurs="1" minOccurs="1">
			</element>
			<element name="FuncImpLOCMean" type="tns:FuncImpLOCMeanType"
				maxOccurs="1" minOccurs="1">
			</element>
			<element name="FuncImpLOCStDev"
				type="tns:FuncImpLOCStDevType" maxOccurs="1" minOccurs="1">
			</element>
		</sequence>
	</complexType>


	<complexType name="BugsParametersType">
		<sequence>
			<element name="BugsPerLOCMean" type="double" maxOccurs="1"
				minOccurs="1">
			</element>
			<element name="BugsPerLOCStDev" type="double" maxOccurs="1"
				minOccurs="1">
			</element>
			<element name="TimeMeanPerLOCSubmission" type="double"
				maxOccurs="1" minOccurs="1">
			</element>
			<element name="TimeStDevPerLOCSubmission" type="double"
				maxOccurs="1" minOccurs="1">
			</element>
			<element name="BugfixTimeMean" type="double" maxOccurs="1"
				minOccurs="1">
			</element>
			<element name="BugFixTimeStDev" type="double" maxOccurs="1"
				minOccurs="1">
			</element>
		</sequence>
	</complexType>

	<complexType name="TestsParametersType">
		<sequence>
			<element name="testingTimeMean" type="double" maxOccurs="1"
				minOccurs="1">
			</element>
			<element name="testingTimeStDev" type="double" maxOccurs="1"
				minOccurs="1">
			</element>
		</sequence>
	</complexType>

	<complexType name="PDParametersType">
		<sequence>
			<element name="linesOfCodeParameters"
				type="tns:LinesOfCodeParametersType" maxOccurs="1" minOccurs="1">
			</element>
			<element name="bugsParameters" type="tns:BugsParametersType"
				maxOccurs="1" minOccurs="1">
			</element>
			<element name="testsParameters"
				type="tns:TestsParametersType" maxOccurs="1" minOccurs="1">
			</element>
		</sequence>
	</complexType>

	<element name="SimulationParameters"
		type="tns:SimulationParametersType">
	</element>


	<complexType name="SimulationParametersType">
		<sequence>
			<element name="initialConditions"
				type="tns:InitialConditionsType" maxOccurs="1" minOccurs="1">
			</element>
			<element name="bmFixedParameters"
				type="tns:BMFixedParametersType" maxOccurs="1" minOccurs="1">
			</element>
			<element name="bmProjectParameters"
				type="tns:BMProjectParametersType" maxOccurs="1" minOccurs="1">
			</element>
			<element name="pdParameters" type="tns:PDParametersType"
				maxOccurs="1" minOccurs="1">
			</element>
		</sequence>
	</complexType>
</schema>

=== GeorgiKhomeriki/Alitheia-Core/metrics/simulation/src/eu/sqooss/metrics/simulation/xml/SimulationConfig.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:SimulationParameters xmlns:tns="http://www.example.org/SimulationSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/SimulationSchema SimulationSchema.xsd ">
  <tns:initialConditions>
    <tns:modules>
      <tns:module>
        <tns:name>module1</tns:name>
        <tns:numberOfPieces>1</tns:numberOfPieces>
      </tns:module>
      <tns:module>
      	<tns:name>module2</tns:name>
      	<tns:numberOfPieces>1</tns:numberOfPieces>
      </tns:module>
    </tns:modules>
    <tns:simulationParameters>
      <tns:simulationSteps>1000</tns:simulationSteps>
      <tns:numberOfRepetitions>200</tns:numberOfRepetitions>
      <tns:timeScale>0.1</tns:timeScale>
    </tns:simulationParameters>
  </tns:initialConditions>
  <tns:bmFixedParameters>
    <tns:programmersInterest>
      <tns:submissionInterest>
        <tns:interest>0.0</tns:interest>
        <tns:interest>0.0</tns:interest>
      </tns:submissionInterest>
      <tns:debuggingInterest>
        <tns:interest>0.15</tns:interest>
        <tns:interest>0.15</tns:interest>
      </tns:debuggingInterest>
      <tns:testingInterest>
        <tns:interest>0.45</tns:interest>
        <tns:interest>0.45</tns:interest>
      </tns:testingInterest>
      <tns:functionalityInterest>
        <tns:interest>0.40</tns:interest>
        <tns:interest>0.40</tns:interest>
      </tns:functionalityInterest>
    </tns:programmersInterest>
    <tns:tasks>
      <tns:releaseFrequency>0.4</tns:releaseFrequency>
      <tns:locIncrementMean>0.4</tns:locIncrementMean>
      <tns:commitsMean>0.2</tns:commitsMean>
    </tns:tasks>
    <tns:calibration>
      <tns:commitsMean>10.0</tns:commitsMean>
      <tns:releasesMean>220.0</tns:releasesMean>
      <tns:contributorsMean>25.0</tns:contributorsMean>
      <tns:locIncremetsMean>220</tns:locIncremetsMean>
    </tns:calibration>
  </tns:bmFixedParameters>
  <tns:bmProjectParameters>
    <tns:aParameters>
      <tns:coreContributors>7</tns:coreContributors>
      <tns:halfLifeOfProgrammersInterest>246.0</tns:halfLifeOfProgrammersInterest>
      <tns:halfLifesStDev>213.0</tns:halfLifesStDev>
    </tns:aParameters>
    <tns:bParameters>
      <tns:qZero>1</tns:qZero>
    </tns:bParameters>
    <tns:cParameters>
      <tns:projectReleaseInterval>60</tns:projectReleaseInterval>
    </tns:cParameters>
  </tns:bmProjectParameters>
  <tns:pdParameters>
    <tns:linesOfCodeParameters>
      <tns:ModulesLOCMean>
        <tns:moduleLOCMean>1000</tns:moduleLOCMean>
        <tns:moduleLOCMean>1000</tns:moduleLOCMean>
      </tns:ModulesLOCMean>
      <tns:ModulesLOCStDev>
        <tns:moduleLOCStDev>2000</tns:moduleLOCStDev>
        <tns:moduleLOCStDev>2000</tns:moduleLOCStDev>
      </tns:ModulesLOCStDev>
      <tns:CompletedLOCMean>
        <tns:completedLOCMean>5000.0</tns:completedLOCMean>
        <tns:completedLOCMean>5000.0</tns:completedLOCMean>
      </tns:CompletedLOCMean>
      <tns:CompletedLOCStDev>
        <tns:completedLOCStDev>1000.0</tns:completedLOCStDev>
        <tns:completedLOCStDev>1000.0</tns:completedLOCStDev>
      </tns:CompletedLOCStDev>
      <tns:FuncImpLOCMean>
        <tns:funcImpLOCMean>27.0</tns:funcImpLOCMean>
        <tns:funcImpLOCMean>27.0</tns:funcImpLOCMean>
      </tns:FuncImpLOCMean>
      <tns:FuncImpLOCStDev>
        <tns:funcImpLOCStDev>115.0</tns:funcImpLOCStDev>
        <tns:funcImpLOCStDev>115.0</tns:funcImpLOCStDev>
      </tns:FuncImpLOCStDev>
    </tns:linesOfCodeParameters>
    <tns:bugsParameters>
      <tns:BugsPerLOCMean>0.004</tns:BugsPerLOCMean>
      <tns:BugsPerLOCStDev>0.003</tns:BugsPerLOCStDev>
      <tns:TimeMeanPerLOCSubmission>0.0117</tns:TimeMeanPerLOCSubmission>
      <tns:TimeStDevPerLOCSubmission>0.0387</tns:TimeStDevPerLOCSubmission>
      <tns:BugfixTimeMean>1.0</tns:BugfixTimeMean>
      <tns:BugFixTimeStDev>3.0</tns:BugFixTimeStDev>
    </tns:bugsParameters>
    <tns:testsParameters>
      <tns:testingTimeMean>0.1</tns:testingTimeMean>
      <tns:testingTimeStDev>0.2</tns:testingTimeStDev>
    </tns:testsParameters>
  </tns:pdParameters>
</tns:SimulationParameters>
